blank_issues_enabled: false

contact_links:
  - name: NameProject 国内镜像 | China Mirror
    url: https://gitee.com/XFTYC/NameProject
    about: 访问国内镜像可以大大降低访问延迟

  - name: NameProject 国内 issues | China Mirror
    url: https://gitee.com/XFTYC/NameProject/issues
    about: 访问国内镜像可以大大降低访问延迟

  - name: NameProject 网站
    url: https://xfty.github.io/NameProject
    about: 基于 github.io 的小型网站